== Uruchomienie z docker-compose:

* Instalacja CLI (opcjonalnie):

    brew install kafka

* Run docker-compose

    sudo docker-compose up

* Sprawd藕 czy UI odpowiada i podczy sie do kafki: http://localhost:8080[kafka-ui]

* Sprawd藕 czy dziaa CLI

** jak zrobie ```brew install kafka```

    kafka-topics

** je偶eli NIE zrobie ```brew install kafka``` to trzeba wywoywa wszystkie kolejne polecenia w kontenerze

    docker exec -it kafka /bin/bash

    kafka-topics


* Utw贸rz topic:

    kafka-topics --bootstrap-server localhost:9092 --topic mynewtopic --create --partitions 3

* Potwierd藕, 偶e si utworzy z 3 partycjami z poziomu CLI lub ui http://localhost:8080/ui/clusters/local/all-topics?perPage=25[kafka-ui/topics] (chwil trzeba poczeka bo musi si odwie偶y)

    kafka-topics --bootstrap-server localhost:9092 --list
    kafka-topics --bootstrap-server localhost:9092 --topic mynewtopic --describe

* Utw贸rz pierwszego consumera (w osobnym terminalu)

    kafka-console-consumer --bootstrap-server localhost:9092 --topic mynewtopic

* Utw贸rz producera (w osobnym terminalu)

    kafka-console-producer --bootstrap-server localhost:9092 --producer-property partitioner.class=org.apache.kafka.clients.producer.RoundRobinPartitioner --topic mynewtopic

* Wpisz jakie wiadomoci (enter == wysanie wiadomoci)

    >jednen
    >dwa
    >trzy

* Zweryfikuj czy consumer je otrzyma

* Utw贸rz kolejnego cosumera (w osobnym terminalu)

    kafka-console-consumer --bootstrap-server localhost:9092 --topic mynewtopic --from-beginning

* Wpisz jakie wiadomoci (enter == wysanie wiadomoci)

    >jednen
    >dwa
    >trzy

* Zweryfikuj 偶e obu consumer贸w je otrzymao i czy widac je w ui
http://localhost:8080/ui/clusters/local/all-topics/mynewtopic/messages?keySerde=String&valueSerde=String&limit=100[kafka-ui]


===  Problem!!! :
Jak sie utworzy consumer贸w w tej samej grupie to kafka przestaje dziaa, poni偶ej kroki

* Utw贸rz topic:

    kafka-topics --bootstrap-server localhost:9092 --topic mynewtopic2 --create --partitions 3

* Potwierd藕, 偶e si utworzy z 3 partycjami

    kafka-topics --bootstrap-server localhost:9092 --list
    kafka-topics --bootstrap-server localhost:9092 --topic mynewtopic2 --describe

* Utw贸rz pierwszego consumera w grupie 1 (w osobnym terminalu)

    kafka-console-consumer --bootstrap-server localhost:9092 --topic mynewtopic2 --group my-first-group

* Utw贸rz drugiego consumera w grupie 1 (w osobnym terminalu)

    kafka-console-consumer --bootstrap-server localhost:9092 --topic mynewtopic2 --group my-first-group

* Utw贸rz producera (w osobnym terminalu)

    kafka-console-producer --bootstrap-server localhost:9092 --producer-property partitioner.class=org.apache.kafka.clients.producer.RoundRobinPartitioner --topic mynewtopic2

* Zweryfikuj czy consumerzy otrzymuj wiadomoci na zmian, nie koniecznie po kolei. [.red]#U mnie czasami kafka przestaje odpowiada 锔#




== Uruchomienie lokalne bez docker贸w:

- Instalacja

    brew install kafka

- Start Zookeeper

    /opt/homebrew/bin/zookeeper-server-start /opt/homebrew/etc/zookeeper/zoo.cfg

- Start Apache Kafka

    /opt/homebrew/bin/kafka-server-start /opt/homebrew/etc/kafka/server.properties
